version: "3.8"

services:
  postgres:
    image: postgres:13
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: "${DB_HOST}"
  